# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychic',
            name='char_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='psychic',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
