# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20171009_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
