# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_remove_psychic_char_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychic',
            name='profession',
            field=models.CharField(choices=[('p(S)ychic', 'S'), ('(W)arrior', 'W'), ('(T)hief', 'T'), ('(M)age', 'M'), ('(C)leric', 'C'), ('Mon(K)', 'K'), ('(P)aladin', 'P'), ('(D)ruid', 'D')], max_length=1),
        ),
    ]
